version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sayup_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "sayup_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build: .
    container_name: sayup_app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: "mysql"
      DB_NAME: "sayup_db"
      DB_USERNAME: "root"
      DB_PASSWORD: "0000"
      # 경로 변경 필요
      FILE_UPLOAD_DIR: "/file/temp"
      API_KEY: "temp"
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
