version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sayup_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "sayup_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/sayup:latest
    container_name: sayup
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env.prod
    environment:
      DB_CONNECTION: "mysql"
      DB_NAME: "sayup_db"
      DB_USERNAME: "root"
      DB_PASSWORD: "0000"
      # 경로 변경 필요
      FILE_UPLOAD_DIR: "tmp/file/userVoice"
      API_KEY: "${CHATGPT_API_KEY}"
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
