# ?? ?? ??
spring:
  application:
    name: SayUp-Prod

  datasource:
    url: jdbc:mysql://${DB_CONNECTION}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# JWT ??
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# ?? ??? ??
file:
  upload-dir: ${FILE_UPLOAD_DIR}

# OpenAI ??
openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${API_KEY}

# Python ?? ??
python:
  server:
    url: ${PYTHON_SERVER_URL}

# ??? ??
kakao:
  client_id: ${KAKAO}
  redirect_uri: ${KAKAO_REDIRECT_URI}

# ?? ??
logging:
  level:
    com.sayup.SayUp: INFO
    org.springframework.security: WARN
    root: WARN
