spring:
  application:
    name: SayUp

  datasource:
    url: jdbc:mysql://${DB_CONNECTION}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-circular-references: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.sayup.SayUp: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: ${JWT_SECRET:SnNvbldlYlRva2VuQXV0aGVudGljYXRpb25XaXRoU3ByaW5nQm9vdFRlc3RQcm9qZWN0U2VjcmV0S2V5Cg==}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

file:
  upload-dir: ${FILE_UPLOAD_DIR}

openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${API_KEY}

python:
  server:
    url: http://127.0.0.1:8000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.sayup.SayUp.controller

kakao:
  client_id: ${KAKAO}
  redirect_uri: http://localhost:8080/api/auth/kakao/callback
