name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # MySQL 서비스
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 0000
          MYSQL_DATABASE: sayup_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Create file upload directory
      run: mkdir -p /tmp/file/temp
      
    - name: Verify MySQL connection
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 3306 -uroot -p0000 -e "SHOW DATABASES;"
        
    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        # 5초 간격으로 최대 60초 동안 시도
        for i in {1..12}; do
          mysql --host 127.0.0.1 --port 3306 -uroot -p0000 -e "SELECT 1" >/dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "MySQL is ready!"
            break
          fi
          echo "MySQL is not ready yet. Waiting 5 seconds..."
          sleep 5
        done
        
        # 마지막 시도
        mysql --host 127.0.0.1 --port 3306 -uroot -p0000 -e "SELECT 1" || (echo "MySQL failed to start" && exit 1)
      
    - name: Build with Gradle (including tests)
      run: ./gradlew build
      env:
        DB_CONNECTION: mysql
        DB_NAME: sayup_db
        DB_USERNAME: root
        DB_PASSWORD: 0000
        DB_HOST: localhost
        FILE_UPLOAD_DIR: /tmp/file/temp
        API_KEY: temp
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sayup:latest,${{ secrets.DOCKERHUB_USERNAME }}/sayup:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sayup:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sayup:buildcache,mode=max
        build-args: |
          DB_CONNECTION=mysql
          DB_NAME=sayup_db
          DB_USERNAME=root
          DB_PASSWORD=0000
          FILE_UPLOAD_DIR=/file/temp
          API_KEY=temp
