name: Docker Image CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: 'sayup_db'
          mysql root password: '0000'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Create file upload directory
      run: mkdir -p /tmp/file/temp
      
    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        for i in {1..30}; do
          if mysqladmin ping -h "127.0.0.1" -u root -p"0000" --silent; then
            echo "MySQL is ready!"
            exit 0
          fi
          echo "Waiting for MySQL... ($i)"
          sleep 2
        done
        echo "MySQL did not become ready in time!"
        exit 1
      
    - name: Build with Gradle (including tests)
      run: ./gradlew build
      env:
        DB_CONNECTION: mysql
        DB_NAME: sayup_db
        DB_USERNAME: root
        DB_PASSWORD: '0000'
        DB_HOST: 127.0.0.1
        FILE_UPLOAD_DIR: /tmp/file/temp
        API_KEY: temp
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sayup:latest,${{ secrets.DOCKERHUB_USERNAME }}/sayup:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sayup:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sayup:buildcache,mode=max
        build-args: |
          DB_CONNECTION=mysql
          DB_NAME=sayup_db
          DB_USERNAME=root
          DB_PASSWORD=0000
          FILE_UPLOAD_DIR=/file/temp
          API_KEY=temp
